### ISSUE TITLE
Load specs from a remote file

### ISSUE THREAD

**Issue by andrsbtrg** [Gizemdem/Mapple-CI-Pipeline#1]
I don't know about the security implications of this, but I have an idea how we can make the use of this Maple tests in speckle automate easier. 

At the moment, if someone wants to create their own specs and run them against a model they have to basically clone this repo to create their own Speckle automation function and write there their own specs. It's a lot of steps where actually the only thing that needs to change is the spec's definition.

We could improve this by enabling passing by function input a url to a GitHub repo containing a 'spec.py' file. Then the maple runner would take care of reading that module and running each one of the specs inside of it. 

This could be done with [this package](https://github.com/operatorequals/httpimport) and a decorator that decorates the spec function

**Comment by Gizemdem** [comment]
With the pull request #6 issue is solved. Now it possible to load the test file from github/gist.

**Comment by Gizemdem** [comment]
With the pull request https://github.com/Gizemdem/Mapple-CI-Pipeline/pull/6 issue is solved. Now it possible to load the test file from github/gist.
