### ISSUE TITLE
improvement: mp.run()

### ISSUE THREAD

**Issue by Gizemdem** [Gizemdem/Mapple-CI-Pipeline#7]
The mp.run should only run for the test specs.  At the moment it will throw an error,  if something else other than function spec passed to the mp.run.

Acceptance Criteria: Throw user friendly error.

**Comment by andrsbtrg** [comment]
I think this is a good way for now to give an early error when what is passed to mp.run is not a function:

https://github.com/andrsbtrg/maple/pull/1

**Comment by andrsbtrg** [comment]
https://github.com/andrsbtrg/maple/pull/2 
This improves on the user experience IMO, because raising Error means the tests that alredy ran will be lost. Instead maple will skip the arguments which are not callable and print a warning.
